-- AlterTable
ALTER TABLE `User` ADD COLUMN `firstName` VARCHAR(191) NULL,
    ADD COLUMN `lastName` VARCHAR(191) NULL,
    ADD COLUMN `schoolClass` VARCHAR(191) NULL,
    ADD COLUMN `schoolName` VARCHAR(191) NULL;
